# Generated by Django 3.1 on 2020-08-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='path',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
