# Generated by Django 3.0.8 on 2020-08-20 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message='Name may not contain forward slashes.',
                        regex='/',
                    )
                ],
            ),
        ),
    ]
