# Generated by Django 3.1 on 2020-09-01 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_folder_name_validator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='path',
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to='core.folder'
            ),
        ),
    ]
