# Generated by Django 3.1.3 on 2020-12-16 19:05

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='blob',
            field=s3_file_field.fields.S3FileField(
                max_length=2000, upload_to=s3_file_field.fields.S3FileField.uuid_prefix_filename
            ),
        ),
    ]
