# Generated by Django 3.1.2 on 2020-10-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_s3_ff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={
                'permissions': (
                    ('read_tree', 'Read access to a tree'),
                    ('write_tree', 'Write access to a tree'),
                    ('admin_tree', 'Admin access to a tree'),
                )
            },
        ),
    ]
