# Generated by Django 3.1.2 on 2020-11-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
