# Generated by Django 3.1.5 on 2021-01-29 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_tree_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'
            ),
            preserve_default=False,
        ),
    ]
