# Generated by Django 3.1.1 on 2020-09-23 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20200912_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='file',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='file',
            name='owner',
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='files',
                to='core.folder',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='sha512',
            field=models.CharField(
                blank=True, db_index=True, default='', editable=False, max_length=128
            ),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveBigIntegerField(default=-1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message='Name may not contain forward slashes.',
                        regex='/',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name='folder',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['folder', 'name'], name='core_file_folder__f8cfaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(
                fields=('folder', 'name'), name='file_siblings_name_unique'
            ),
        ),
    ]
