# Generated by Django 3.1.1 on 2020-09-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200923_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='folder',
            name='user_metadata',
            field=models.JSONField(default=dict),
        ),
    ]
