# Generated by Django 3.1.1 on 2020-09-29 14:29

from django.db import migrations, models
import django.db.models.deletion

import dkc.core.models.metadata


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200923_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='user_metadata',
            field=dkc.core.models.metadata.UserMetadataField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='folder',
            name='user_metadata',
            field=dkc.core.models.metadata.UserMetadataField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='child_folders',
                to='core.folder',
            ),
        ),
        migrations.AlterField(
            model_name='folder',
            name='root_folder',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='core.folder',
            ),
        ),
    ]
