# Generated by Django 3.1.5 on 2021-01-31 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions

import dkc.core.models.quota


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_non_nullable_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quota',
            name='allocation',
        ),
        migrations.AddField(
            model_name='quota',
            name='allowed',
            field=models.PositiveBigIntegerField(default=dkc.core.models.quota._default_user_quota),
        ),
        migrations.AddField(
            model_name='quota',
            name='used',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tree',
            name='quota',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='trees',
                to='core.quota',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quota',
            name='user',
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quota',
                to='auth.user',
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='quota',
            constraint=models.CheckConstraint(
                check=models.Q(used__lte=django.db.models.expressions.F('allowed')),
                name='used_lte_allowed',
            ),
        ),
    ]
