# Generated by Django 3.1.6 on 2021-02-03 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='quota',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
