# Generated by Django 3.1.2 on 2020-10-08 17:37

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations, models
import django.db.models.deletion

import dkc.core.models.user_quota


def default_owner():
    user = User.objects.first()
    return user and user.pk


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_auto_20201007_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderQuota',
            fields=[
                (
                    'folder',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='quota',
                        serialize=False,
                        to='core.folder',
                    ),
                ),
                ('used', models.PositiveBigIntegerField(default=0)),
                ('allowed', models.PositiveBigIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(
                default=default_owner, on_delete=django.db.models.deletion.CASCADE, to='auth.user'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userquota',
            name='allowed',
            field=models.PositiveBigIntegerField(
                default=dkc.core.models.user_quota._default_user_quota
            ),
        ),
        migrations.AlterField(
            model_name='folderquota',
            name='allowed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
