# Generated by Django 3.1.7 on 2021-03-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_file_pre_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='legacy_file_id',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='file',
            name='legacy_item_id',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddField(
            model_name='folder',
            name='legacy_id',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(
                condition=models.Q(_negated=True, legacy_file_id=''),
                fields=['legacy_file_id'],
                name='file_legacy_file_id_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(
                condition=models.Q(_negated=True, legacy_item_id=''),
                fields=['legacy_item_id'],
                name='file_legacy_item_id_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(
                condition=models.Q(_negated=True, legacy_id=''),
                fields=['legacy_id'],
                name='folder_legacy_id_idx',
            ),
        ),
    ]
