# Generated by Django 3.1.6 on 2021-02-09 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_file_pre_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUpload',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(editable=False)),
                (
                    'creator',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='authorized_uploads',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'folder',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='authorized_uploads',
                        to='core.folder',
                    ),
                ),
            ],
        ),
    ]
