# Generated by Django 3.1.2 on 2020-10-07 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_merge_default_site'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quota',
            new_name='UserQuota',
        ),
        migrations.AlterField(
            model_name='file',
            name='creator',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name='userquota',
            name='id',
        ),
        migrations.AlterField(
            model_name='userquota',
            name='allocation',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.RenameField(
            model_name='userquota',
            old_name='allocation',
            new_name='allowed',
        ),
        migrations.AddField(
            model_name='userquota',
            name='used',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userquota',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name='quota',
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
