# Generated by Django 3.1.2 on 2020-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201025_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='size',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
