# Generated by Django 3.1.2 on 2020-10-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_folder_size'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.CheckConstraint(
                check=models.Q(depth__lte=30), name='folder_max_depth'
            ),
        ),
    ]
